spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    password: root
    username: postgres
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
